import "dotenv/config";
import { loadConfig } from "../config";
import { StateStore } from "../services/stateStore";
import { Scheduler } from "../services/scheduler";
import { createBullMQConnection } from "../services/redisProvider";
import { Queue } from "bullmq";
import { QUEUE_NAMES, DEFAULT_JOB_OPTIONS } from "../queues/queueRegistry";
import type { QueueName } from "../queues/queueRegistry";
import { UserRepository } from "../modules/user/userRepository";
import { makeJobId, todayKey } from "../queues/jobs";
import type { IpSyncJob } from "../queues/jobs";
import { TelegramService } from "../services/telegramService";

async function main() {
  const config = loadConfig();
  const command = process.argv[2];

  if (!["tokens", "ipsync", "trade", "monitor", "reconcile"].includes(command)) {
    console.error("Usage: npx ts-node loadTestTrigger.ts <tokens|ipsync|trade|monitor|reconcile>");
    process.exit(1);
  }

  const store = new StateStore(config);
  await store.connect();

  const redis = createBullMQConnection(config);

  const queues = new Map<QueueName, Queue>();
  for (const name of Object.values(QUEUE_NAMES)) {
    queues.set(
      name,
      new Queue(name, {
        connection: redis,
        defaultJobOptions: DEFAULT_JOB_OPTIONS[name],
      }),
    );
  }

  // Create dummy telegram service so we can instantiate Scheduler
  const dummyTelegram = new TelegramService(config.telegram.botToken, config.telegram.loggerChatId);
  const scheduler = new Scheduler(config, dummyTelegram, null as any, queues, store, redis);

  console.log(`🚀 Triggering phase: ${command}`);

  try {
    switch (command) {
      case "tokens":
        await scheduler["enqueueTokenRenewalJobs"](); // Using bracket notation to bypass private
        console.log("✅ Token renewal jobs enqueued.");
        break;

      case "ipsync":
        const ipSyncQueue = queues.get(QUEUE_NAMES.IP_SYNC);
        if (!ipSyncQueue) throw new Error("IP sync queue missing");

        const userRepo = new UserRepository(store.pool);
        const users = await userRepo.getActiveUsers();
        let enqueued = 0;

        for (const user of users) {
          if (!user.dhan_client_id) continue;
          // For ipsync we assume token exists (generated by previous step)
          const hasToken = await redis.exists(`token:${user.id}`);
          if (!hasToken) continue;

          const jobId = makeJobId(["ip-sync", user.id, todayKey(), "loadtest", Date.now()]);
          await ipSyncQueue.add(
            "ip-sync",
            {
              userId: user.id,
              action: "IP_SYNC",
              dhanClientId: user.dhan_client_id,
              traceId: `loadtest-ipsync-${Date.now()}`,
              enqueuedAt: new Date().toISOString(),
            } as IpSyncJob,
            { jobId },
          );
          enqueued++;
        }
        console.log(`✅ Enqueued ${enqueued} IP_SYNC jobs.`);
        break;

      case "trade":
        const resTrade = await scheduler.runTradeScan();
        console.log(resTrade);
        break;

      case "monitor":
        const resMonitor = await scheduler.runMonitor();
        console.log(resMonitor);
        break;

      case "reconcile":
        const resReconcile = await scheduler.runReconciliation();
        console.log(resReconcile);
        break;
    }
  } catch (err) {
    console.error(`❌ Error executing ${command}:`, err);
  } finally {
    // Cleanup
    for (const q of queues.values()) {
      await q.close();
    }
    redis.disconnect();
    await store.disconnect();
    process.exit(0);
  }
}

main().catch(console.error);
